spring.application.name=expensetracking
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

expensetracking.app.jwtSecret= ======================expensetracking=Spring===========================
expensetracking.app.jwtExpirationMs= 86400000