spring.datasource.url=jdbc:postgresql://postgresqllserver.postgres.database.azure.com:5432/postgres?sslmode=require
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

expensetracking.app.jwtSecret=${JWT_SECRET}
expensetracking.app.jwtExpirationMs= 86400000